openapi: 3.0.1
info:
  title: TuneCast
  description: The TuneCast API enables media server interaction
  version: 1.0.0
paths:
  /library:
    get:
      summary: Browse the media library
      operationId: getLibrary
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LibraryItem"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    LibraryItem:
      type: object
      properties:
        itemName:
          type: string
        itemType:
          type: string
          default: folder
          enum:
            - folder
            - file
        itemLink:
          type: string
